[package]
name = "boxedmino"
version = "0.0.1"
edition = "2021"

[dependencies]
copypasta = "0.10.1"
home = "0.5.9"
open = "5.3.0"
rfd = "0.15.0"
serde = { "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
slint = "1.8.0"

[build-dependencies]
slint-build = "1.8.0"
